/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ItemController;
import controllers.SaleController;
import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import models.Item;
import models.Sale;
import utils.MySQLConn;

public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
//        this.tbInv.setDefaultEditor(Object.class, null);
//        setDataForInventory("");
//        setItemsOfMercSale();
//        setItemsOfConsSale();
        this.setLocationRelativeTo(null);
    }
    

//    private void setItemsOfMercSale(){
//        try {
//            cnx = MySQLConn.getConn();
//            mercItemsData = new ItemController().getListItems(cnx, "mercancias");
//            this.cbItemMerc.removeAllItems();
//            for(Item mercItem : mercItemsData){
//                this.cbItemMerc.addItem(mercItem.getNombre());
//            }
//            mercData = new SaleController().getAllSales(cnx, "mercancias");
//
//            DefaultTableModel model = new DefaultTableModel();
//
//            model.setColumnIdentifiers(saleHeaders);
//
//            this.tbSaleMerc.setModel(model);
//
//            for(Sale sl : mercData){
//                String categoria = sl.getCategoria().substring(0,1).toUpperCase() + sl.getCategoria().substring(1);
//                model.addRow(new Object[]{ sl.getId(), sl.getNombre(), categoria, sl.getPrecio(), sl.getCantidad(), sl.getTotal(), sl.getFecha() } );
//            }
//            
//        }catch (ClassNotFoundException | SQLException ex) {
//            System.out.println(ex.getMessage());
//            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }
    
//    private void setItemsOfConsSale(){
//        try {
//            cnx = MySQLConn.getConn();
//            consItemsData = new ItemController().getListItems(cnx, "insumos");
//            this.cbItemCons.removeAllItems();
//            for(Item consItem : consItemsData){
//                this.cbItemCons.addItem(consItem.getNombre());
//            }
//            consData = new SaleController().getAllSales(cnx, "insumos");
//
//            DefaultTableModel model = new DefaultTableModel();
//
//            model.setColumnIdentifiers(saleHeaders);
//
//            this.tbSaleCons.setModel(model);
//
//            for(Sale sl : consData){
//                String categoria = sl.getCategoria().substring(0,1).toUpperCase() + sl.getCategoria().substring(1);
//                model.addRow(new Object[]{ sl.getId(), sl.getNombre(), categoria, sl.getPrecio(), sl.getCantidad(), sl.getTotal(), sl.getFecha() } );
//            }
//            
//        }catch (ClassNotFoundException | SQLException ex) {
//            System.out.println(ex.getMessage());
//            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error al conectar con la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    }
//    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInit.setText("Iniciar");
        btnInit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInitMouseClicked(evt);
            }
        });
        getContentPane().add(btnInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido a GPR Caliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_1.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInitMouseClicked
        this.setVisible(false);
        new Inventory().setVisible(true);
    }//GEN-LAST:event_btnInitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
